apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: warehouse-tessera-job
  namespace: warehouse-bes
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: warehouse-tessera-job
  chart:
    path: platforms/hyperledger-besu/charts/tessera_key_mgmt
    git: https://github.com/jagpreetsinghsasan/bevel.git
    ref: localtest
  values:
    metadata:
      name: warehouse-tessera-job
      namespace: warehouse-bes
    peer:
      name: warehouse        
    image:      
      repository: quorumengineering/tessera:hashicorp-21.7.3
      pullSecret: regcred
    vault:
      address: http://192.168.1.10:8200
      secretengine: secretsv2
      authpath: besuwarehouse
      role: vault-role
      keyprefix: warehouse-bes/crypto
      serviceaccountname: vault-auth
      tmprefix: secretsv2/data/warehouse-bes/crypto
