apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: store-tessera-job
  namespace: store-bes
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: store-tessera-job
  chart:
    path: platforms/hyperledger-besu/charts/tessera_key_mgmt
    git: https://github.com/jagpreetsinghsasan/bevel.git
    ref: localtest
  values:
    metadata:
      name: store-tessera-job
      namespace: store-bes
    peer:
      name: store        
    image:      
      repository: quorumengineering/tessera:hashicorp-21.7.3
      pullSecret: regcred
    vault:
      address: http://192.168.1.10:8200
      secretengine: secretsv2
      authpath: besustore
      role: vault-role
      keyprefix: store-bes/crypto
      serviceaccountname: vault-auth
      tmprefix: secretsv2/data/store-bes/crypto
