apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: storetessera
  namespace: store-bes
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: storetessera
  helmVersion: v3
  chart:
    git: https://github.com/jagpreetsinghsasan/bevel.git
    ref: localtest
    path: platforms/hyperledger-besu/charts/node_tessera  
  values:
    replicaCount: 1
    metadata:
      namespace: store-bes
      labels:
    images:      
      alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
      tessera: quorumengineering/tessera:hashicorp-21.7.3
      busybox: busybox
      mysql: mysql/mysql-server:5.7
      imagePullSecret: regcred
    tessera:
      name: store-tessera
      dbname: demodb      
      dburl: "jdbc:mysql://store-tessera:3306/demodb"
      dbusername: demouser
      tls: "STRICT"
      
      url: "https://store-tessera.store-bes:443"
      
      clienturl: "https://store-tessera:8888"
      othernodes:
        - url: https://carrier-tessera.carrier-bes
      trust: "TOFU"
      
     
      servicetype: NodePort
      ports:
        tm: 443        
        db: 3306
        client: 8888
      mountPath: /etc/tessera/data
      ambassadorSecret: store-ambassador-certs
    vault:
      address: http://192.168.1.10:8200
      secretengine: secretsv2
      tmsecretpath: store-bes/crypto/store/tm
      secretprefix: secretsv2/data/store-bes/crypto/store
      serviceaccountname: vault-auth
      keyname: credentials
      tm_keyname: tm
      tlsdir: tls
      role: vault-role
      authpath: besustore
      
    proxy:
      provider: "none"
      external_url: store.store-bes
      portTM: 443      
    storage:
      storageclassname: minikubestorageclass
      storagesize: 1Gi
      dbstorage: 1Gi
