apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: approve-manufacturer-allchannel-peer0supplychain1-1
  namespace: manufacturer-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: approve-manufacturer-allchannel-peer0supplychain1-1
  chart:
    git: https://github.com/jagpreetsinghsasan/bevel.git
    ref: localtest
    path: platforms/hyperledger-fabric/charts/approve_chaincode
  values:
    metadata:
      namespace: manufacturer-net
      images:
        fabrictools: hyperledger/fabric-tools:2.2.2
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    peer:
      name: peer0
      address: peer0.manufacturer-net:7051
      localmspid: manufacturerMSP
      loglevel: debug
      tlsstatus: true
    vault:
      role: vault-role
      address: http://192.168.1.10:8200
      authpath: localmanufacturer-net-auth
      adminsecretprefix: secretsv2/data/crypto/peerOrganizations/manufacturer-net/users/admin 
      orderersecretprefix: secretsv2/data/crypto/peerOrganizations/manufacturer-net/orderer
      serviceaccountname: vault-auth
      imagesecretname: regcred
      tls: false
    orderer:
      address: orderer1.supplychain-net:7050
    chaincode:
      builder: hyperledger/fabric-ccenv:2.2.2
      name: supplychain
      version: 1
      sequence: 1
      commitarguments: '\"init\",\"\"'
      endorsementpolicies:  ''
    channel:
      name: allchannel
