apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: supplychain-orderer1
  namespace: supplychain-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: supplychain-orderer1
  chart:
    git: https://github.com/jagpreetsinghsasan/bevel.git
    ref: localtest
    path: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: supplychain-net
      images:
        orderer: hyperledger/fabric-orderer:2.2.2
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    annotations:  
      service:
        - example1: example2
      pvc:
      deployment:
    orderer:
      name: orderer1
      loglevel: info
      localmspid: supplychainMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: raft

    storage:
      storageclassname: supplychainsc
      storagesize: 512Mi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://192.168.1.10:8200
      role: vault-role
      authpath: localsupplychain-net-auth
      secretprefix: secretsv2/data/crypto/ordererOrganizations/supplychain-net/orderers/orderer1.supplychain-net
      imagesecretname: regcred
      serviceaccountname: vault-auth

    proxy:
      provider: none
      external_url_suffix: develop.local.com

    genesis: |-
      CiIaINKUZzYW6WkV4pqgjpCw7uhcfx4IzQPIR44av369gnXmEo5eCoteCoheCngKWggBEAEaBgiY
      t8aVBiIKc3lzY2hhbm5lbCpAMDRiZDhiMGYxZTIyN2NkMTFkMDhlNjM0ZWZiOTE4MmY5YjJmZWE0
      MDFhN2FhMjAwYmIyNmZlNGJhNjBkY2IxOBIaEhiCjrFbNf9hblQR+hZ75RnL31F0NZU/faQSi10K
      iF0ShV0SiSsKB09yZGVyZXIS/SoSyhYKDnN1cHBseWNoYWluTVNQErcWGsMUCgNNU1ASuxQSsBQS
      rRQKDnN1cHBseWNoYWluTVNQEvEFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNBREND
      QWFhZ0F3SUJBZ0lVWFdLWVpKRGJyNE1WUWlOeHlQOHByMmwvYVM0d0NnWUlLb1pJemowRUF3SXcK
      WGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dU
      Rzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndi
      SGxqYUdGcGJpMXVaWFF3CkhoY05Nakl3TmpJeE1UQXdOREUwV2hjTk1qVXdOREV3TVRBd05ERTBX
      akJlTVFzd0NRWURWUVFHRXdKSFFqRVAKTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3RFFZRFZRUUhE
      QVpNYjI1a2IyNHhFREFPQmdOVkJBb01CMDl5WkdWeQpaWEl4R3pBWkJnTlZCQU1NRW1OaExuTjFj
      SEJzZVdOb1lXbHVMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VIQTBJQUJFN1hY
      RWtKR1BDNThTZ2FLRTQ4bDFsR2dxcmFZb3Q2QmVtNEhTcFBGeXRzV0F6bVBseHIKZmFxa1FGeElv
      NDNXS2VCaGJrSHpFV1RCMUdLcHBsenIvWVdqUWpCQU1BOEdBMVVkRXdFQi93UUZNQU1CQWY4dwpE
      Z1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCUzZxcHM3TDJKNGRpYW1TRGxLazM5MVBI
      Q09xVEFLCkJnZ3Foa2pPUFFRREFnTklBREJGQWlFQW4va2tDOGtjQkZ5NW1icFFnUXA0L2JFYTgv
      U2pCMzhZZngyYTJWMlAKdUhRQ0lIa0hkSmdLWFgxQnhXR3BPTm5GenJLeCtYNHQ4SjNWblBKSDBk
      ZmRXR2lICi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIqIILS0tLS1CRUdJTiBDRVJUSUZJQ0FU
      RS0tLS0tCk1JSUM0VENDQW9pZ0F3SUJBZ0lVZUNLZ3ZLTEZxbVlOa0lUbU5nRTBlWU9PZmZZd0Nn
      WUlLb1pJemowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJq
      RVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZR
      UUREQkpqWVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05Nakl3TmpJeE1UQXhNakF3V2hjTk1q
      TXdOakl4TVRBeE56QXdXakJzTVFzd0NRWURWUVFHRXdKSFFqRWIKTUJrR0ExVUVCeE1TTlRFdU5U
      QXZMVEF1TVRNdlRHOXVaRzl1TVJBd0RnWURWUVFLRXdkUGNtUmxjbVZ5TVE0dwpEQVlEVlFRTEV3
      VmhaRzFwYmpFZU1Cd0dBMVVFQXd3VlFXUnRhVzVBYzNWd2NHeDVZMmhoYVc0dGJtVjBNRmt3CkV3
      WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFdEpTRnArUUJIOE1SSjhrWmRxVHplRXVFU1Fj
      eFNxSEEKT3RGaVVLZVZGbnVPNTI1SlBSaGZucktKa0RpMC8xZ0dMRldZc2JlOGFmNWVuc1JnVW9Z
      SEhxT0NBUlF3Z2dFUQpNQTRHQTFVZER3RUIvd1FFQXdJSGdEQU1CZ05WSFJNQkFmOEVBakFBTUIw
      R0ExVWREZ1FXQkJTU042eXFvRWxHCmhzb2lGT1BqeFFBWk5adXZ6REFmQmdOVkhTTUVHREFXZ0JT
      NnFwczdMMko0ZGlhbVNEbEtrMzkxUEhDT3FUQWsKQmdOVkhSRUVIVEFiZ2hsallTMTBiMjlzY3kw
      NE5XUTNOVFprWkdKbUxXaHdZbkZyTUlHSkJnZ3FBd1FGQmdjSQpBUVI5ZXlKaGRIUnljeUk2ZXlK
      aFltRmpMbWx1YVhRaU9pSjBjblZsSWl3aVlXUnRhVzRpT2lKMGNuVmxJaXdpCmFHWXVRV1ptYVd4
      cFlYUnBiMjRpT2lJaUxDSm9aaTVGYm5KdmJHeHRaVzUwU1VRaU9pSkJaRzFwYmtCemRYQncKYkhs
      amFHRnBiaTF1WlhRaUxDSm9aaTVVZVhCbElqb2lZV1J0YVc0aWZYMHdDZ1lJS29aSXpqMEVBd0lE
      UndBdwpSQUlnSE1EdHpFeFlrcWFBcWNIeXZKS1Bvd0lnRE9iLzIvZU5zaXRQUTMvcEJFVUNJRkRw
      WGtvZFNZamNENFhLCmsrZ2t6NmlYVWl0anduSi8zS1hrMlFkMm4vTWEKLS0tLS1FTkQgQ0VSVElG
      SUNBVEUtLS0tLQpCDgoEU0hBMhIGU0hBMjU2SvEFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t
      Ck1JSUNBRENDQWFhZ0F3SUJBZ0lVWFdLWVpKRGJyNE1WUWlOeHlQOHByMmwvYVM0d0NnWUlLb1pJ
      emowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBH
      QTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpq
      WVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05Nakl3TmpJeE1UQXdOREUwV2hjTk1qVXdOREV3
      TVRBd05ERTBXakJlTVFzd0NRWURWUVFHRXdKSFFqRVAKTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3
      RFFZRFZRUUhEQVpNYjI1a2IyNHhFREFPQmdOVkJBb01CMDl5WkdWeQpaWEl4R3pBWkJnTlZCQU1N
      RW1OaExuTjFjSEJzZVdOb1lXbHVMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VI
      QTBJQUJFN1hYRWtKR1BDNThTZ2FLRTQ4bDFsR2dxcmFZb3Q2QmVtNEhTcFBGeXRzV0F6bVBseHIK
      ZmFxa1FGeElvNDNXS2VCaGJrSHpFV1RCMUdLcHBsenIvWVdqUWpCQU1BOEdBMVVkRXdFQi93UUZN
      QU1CQWY4dwpEZ1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCUzZxcHM3TDJKNGRpYW1T
      RGxLazM5MVBIQ09xVEFLCkJnZ3Foa2pPUFFRREFnTklBREJGQWlFQW4va2tDOGtjQkZ5NW1icFFn
      UXA0L2JFYTgvU2pCMzhZZngyYTJWMlAKdUhRQ0lIa0hkSmdLWFgxQnhXR3BPTm5GenJLeCtYNHQ4
      SjNWblBKSDBkZmRXR2lICi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KGgZBZG1pbnMiNwoHV3Jp
      dGVycxIsEiIIARIeEggSBggBEgIIABoSEhAKDnN1cHBseWNoYWluTVNQGgZBZG1pbnMiOAoGQWRt
      aW5zEi4SJAgBEiASCBIGCAESAggAGhQSEgoOc3VwcGx5Y2hhaW5NU1AQARoGQWRtaW5zIjsKC0Vu
      ZG9yc2VtZW50EiwSIggBEh4SCBIGCAESAggAGhISEAoOc3VwcGx5Y2hhaW5NU1AaBkFkbWlucyI3
      CgdSZWFkZXJzEiwSIggBEh4SCBIGCAESAggAGhISEAoOc3VwcGx5Y2hhaW5NU1AaBkFkbWlucyoG
      QWRtaW5zGoISCg1Db25zZW5zdXNUeXBlEvAREuURCghldGNkcmFmdBLYEQrBEQoYb3JkZXJlcjEu
      c3VwcGx5Y2hhaW4tbmV0EIo3Gs8ILS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURBVEND
      QXFtZ0F3SUJBZ0lVU3h2QmZPeDNHb21nOXBRb2ZINnR5bmxmV3Mwd0NnWUlLb1pJemowRUF3SXcK
      WGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dU
      Rzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndi
      SGxqYUdGcGJpMXVaWFF3CkhoY05Nakl3TmpJeE1UQXhNakF3V2hjTk1qTXdOakl4TVRBeE56QXdX
      akJ4TVFzd0NRWURWUVFHRXdKSFFqRWIKTUJrR0ExVUVCeE1TTlRFdU5UQXZMVEF1TVRNdlRHOXVa
      Rzl1TVJBd0RnWURWUVFLRXdkUGNtUmxjbVZ5TVJBdwpEZ1lEVlFRTEV3ZHZjbVJsY21WeU1TRXdI
      d1lEVlFRREV4aHZjbVJsY21WeU1TNXpkWEJ3YkhsamFHRnBiaTF1ClpYUXdXVEFUQmdjcWhrak9Q
      UUlCQmdncWhrak9QUU1CQndOQ0FBUm5GMlJVRFIwM0srWjFKRlZaUHZCYTZBKy8KclpQUHlQVWxF
      VmN5RFpNai9Zd0Z2RXlyZFl3RXFRc2cyNWlDUjFHVk1KMUhFbjlEcXNZWklJOG5hMnVXbzRJQgpN
      RENDQVN3d0RnWURWUjBQQVFIL0JBUURBZ09vTUIwR0ExVWRKUVFXTUJRR0NDc0dBUVVGQndNQkJn
      Z3JCZ0VGCkJRY0RBakFNQmdOVkhSTUJBZjhFQWpBQU1CMEdBMVVkRGdRV0JCU0R6NnhnbFZiNjBi
      Rnl1bUZ0aHQraUxGUmkKZURBZkJnTlZIU01FR0RBV2dCUzZxcHM3TDJKNGRpYW1TRGxLazM5MVBI
      Q09xVEEvQmdOVkhSRUVPREEyZ2hodgpjbVJsY21WeU1TNXpkWEJ3YkhsamFHRnBiaTF1WlhTQ0dt
      OXlaR1Z5WlhJeExtUmxkbVZzYjNBdWJHOWpZV3d1ClkyOXRNR3dHQ0NvREJBVUdCd2dCQkdCN0lt
      RjBkSEp6SWpwN0ltaG1Ma0ZtWm1sc2FXRjBhVzl1SWpvaUlpd2kKYUdZdVJXNXliMnhzYldWdWRF
      bEVJam9pYjNKa1pYSmxjakV1YzNWd2NHeDVZMmhoYVc0dGJtVjBJaXdpYUdZdQpWSGx3WlNJNklt
      OXlaR1Z5WlhJaWZYMHdDZ1lJS29aSXpqMEVBd0lEUmdBd1F3SWZhWmhFMkVXMThyODM3b3JtCk5B
      VSt3czhDdGxUaHZqcS9kSVlMMTlnNDlRSWdVQXpCbWE2T0ltYWZVN3lRMkdCK05mdm5DYzQyR0lF
      ZE9aK28KRi9PcS80TT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoizwgtLS0tLUJFR0lOIENF
      UlRJRklDQVRFLS0tLS0KTUlJREFUQ0NBcW1nQXdJQkFnSVVTeHZCZk94M0dvbWc5cFFvZkg2dHlu
      bGZXczB3Q2dZSUtvWkl6ajBFQXdJdwpYakVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJr
      eHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZFBjbVJsY21WeU1S
      c3dHUVlEVlFRRERCSmpZUzV6ZFhCd2JIbGphR0ZwYmkxdVpYUXcKSGhjTk1qSXdOakl4TVRBeE1q
      QXdXaGNOTWpNd05qSXhNVEF4TnpBd1dqQnhNUXN3Q1FZRFZRUUdFd0pIUWpFYgpNQmtHQTFVRUJ4
      TVNOVEV1TlRBdkxUQXVNVE12VEc5dVpHOXVNUkF3RGdZRFZRUUtFd2RQY21SbGNtVnlNUkF3CkRn
      WURWUVFMRXdkdmNtUmxjbVZ5TVNFd0h3WURWUVFERXhodmNtUmxjbVZ5TVM1emRYQndiSGxqYUdG
      cGJpMXUKWlhRd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DQUFSbkYyUlVEUjAzSyta
      MUpGVlpQdkJhNkErLwpyWlBQeVBVbEVWY3lEWk1qL1l3RnZFeXJkWXdFcVFzZzI1aUNSMUdWTUox
      SEVuOURxc1laSUk4bmEydVdvNElCCk1EQ0NBU3d3RGdZRFZSMFBBUUgvQkFRREFnT29NQjBHQTFV
      ZEpRUVdNQlFHQ0NzR0FRVUZCd01CQmdnckJnRUYKQlFjREFqQU1CZ05WSFJNQkFmOEVBakFBTUIw
      R0ExVWREZ1FXQkJTRHo2eGdsVmI2MGJGeXVtRnRodCtpTEZSaQplREFmQmdOVkhTTUVHREFXZ0JT
      NnFwczdMMko0ZGlhbVNEbEtrMzkxUEhDT3FUQS9CZ05WSFJFRU9EQTJnaGh2CmNtUmxjbVZ5TVM1
      emRYQndiSGxqYUdGcGJpMXVaWFNDR205eVpHVnlaWEl4TG1SbGRtVnNiM0F1Ykc5allXd3UKWTI5
      dE1Hd0dDQ29EQkFVR0J3Z0JCR0I3SW1GMGRISnpJanA3SW1obUxrRm1abWxzYVdGMGFXOXVJam9p
      SWl3aQphR1l1Ulc1eWIyeHNiV1Z1ZEVsRUlqb2liM0prWlhKbGNqRXVjM1Z3Y0d4NVkyaGhhVzR0
      Ym1WMElpd2lhR1l1ClZIbHdaU0k2SW05eVpHVnlaWElpZlgwd0NnWUlLb1pJemowRUF3SURSZ0F3
      UXdJZmFaaEUyRVcxOHI4Mzdvcm0KTkFVK3dzOEN0bFRodmpxL2RJWUwxOWc0OVFJZ1VBekJtYTZP
      SW1hZlU3eVEyR0IrTmZ2bkNjNDJHSUVkT1orbwpGL09xLzRNPQotLS0tLUVORCBDRVJUSUZJQ0FU
      RS0tLS0tChISCgU1MDBtcxAKGAEgBSiAgIAIGgZBZG1pbnMaIgoJQmF0Y2hTaXplEhUSCwgKEICA
      gDEYgIBAGgZBZG1pbnMaHgoMQmF0Y2hUaW1lb3V0Eg4SBAoCMnMaBkFkbWlucxofChNDaGFubmVs
      UmVzdHJpY3Rpb25zEggaBkFkbWlucxokCgxDYXBhYmlsaXRpZXMSFBIKCggKBFYyXzASABoGQWRt
      aW5zIiIKBkFkbWlucxIYEg4IAxIKCgZBZG1pbnMQAhoGQWRtaW5zIioKD0Jsb2NrVmFsaWRhdGlv
      bhIXEg0IAxIJCgdXcml0ZXJzGgZBZG1pbnMiIgoHUmVhZGVycxIXEg0IAxIJCgdSZWFkZXJzGgZB
      ZG1pbnMiIgoHV3JpdGVycxIXEg0IAxIJCgdXcml0ZXJzGgZBZG1pbnMqBkFkbWlucxK1LwoLQ29u
      c29ydGl1bXMSpS8S2i4KFVN1cHBseUNoYWluQ29uc29ydGl1bRLALhKxFwoPbWFudWZhY3R1cmVy
      TVNQEp0XGqUVCgNNU1ASnRUSkhUSjxUKD21hbnVmYWN0dXJlck1TUBKBBi0tLS0tQkVHSU4gQ0VS
      VElGSUNBVEUtLS0tLQpNSUlDQ3pDQ0FiS2dBd0lCQWdJVVQ4UmJnbHRRUjJsQXE4SGQ4U0JMZkE2
      QUQ1OHdDZ1lJS29aSXpqMEVBd0l3ClpERUxNQWtHQTFVRUJoTUNRMGd4RHpBTkJnTlZCQWdNQmxw
      MWNtbGphREVQTUEwR0ExVUVCd3dHV25WeWFXTm8KTVJVd0V3WURWUVFLREF4TllXNTFabUZqZEhW
      eVpYSXhIREFhQmdOVkJBTU1FMk5oTG0xaGJuVm1ZV04wZFhKbApjaTF1WlhRd0hoY05Nakl3TmpJ
      eE1UQXdOakUyV2hjTk1qVXdOREV3TVRBd05qRTJXakJrTVFzd0NRWURWUVFHCkV3SkRTREVQTUEw
      R0ExVUVDQXdHV25WeWFXTm9NUTh3RFFZRFZRUUhEQVphZFhKcFkyZ3hGVEFUQmdOVkJBb00KREUx
      aGJuVm1ZV04wZFhKbGNqRWNNQm9HQTFVRUF3d1RZMkV1YldGdWRXWmhZM1IxY21WeUxXNWxkREJa
      TUJNRwpCeXFHU000OUFnRUdDQ3FHU000OUF3RUhBMElBQkhueDZDek0xNVRXdHMweUJwWmQ5RGdn
      M1JwUERpQytidFl0Cm5wV0s0NW5Ma2tMcXh5Q1hhMWJNcUplbEVuYWFLQ3VVT2dTNDZqckpmZG1p
      amluN3hGZWpRakJBTUE4R0ExVWQKRXdFQi93UUZNQU1CQWY4d0RnWURWUjBQQVFIL0JBUURBZ0dt
      TUIwR0ExVWREZ1FXQkJTcC9VUVNhd01TWDVoTQo3MGxCNEpqRk5YMUMrakFLQmdncWhrak9QUVFE
      QWdOSEFEQkVBaUFWWk9yamVSRWdvV1NRbTFLTDBQVGs0MDF1CjdqNWpWcTdZWkoxcjE4NVNHd0ln
      S0R2T2VJYjBkWkVvREhsSS9PMk01QXh1enE5bHUwSXdaUkpIMzYvTDlvWT0KLS0tLS1FTkQgQ0VS
      VElGSUNBVEUtLS0tLQoi4wgtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJRER6Q0NBcmFn
      QXdJQkFnSVVWK1ptWVZORWxwMVRMU1Z6M2grRnByRTlpVkV3Q2dZSUtvWkl6ajBFQXdJdwpaREVM
      TUFrR0ExVUVCaE1DUTBneER6QU5CZ05WQkFnTUJscDFjbWxqYURFUE1BMEdBMVVFQnd3R1duVnlh
      V05vCk1SVXdFd1lEVlFRS0RBeE5ZVzUxWm1GamRIVnlaWEl4SERBYUJnTlZCQU1NRTJOaExtMWhi
      blZtWVdOMGRYSmwKY2kxdVpYUXdIaGNOTWpJd05qSXhNVEF4TXpBd1doY05Nak13TmpJeE1UQXhP
      REF3V2pDQmhqRUxNQWtHQTFVRQpCaE1DUTBneEdqQVlCZ05WQkFjVEVUUTNMak00THpndU5UUXZX
      blZ5YVdOb01SVXdFd1lEVlFRS0V3eE5ZVzUxClptRmpkSFZ5WlhJeEl6QU1CZ05WQkFzVEJXRmti
      V2x1TUJNR0ExVUVDeE1NYldGdWRXWmhZM1IxY21WeU1SOHcKSFFZRFZRUUREQlpCWkcxcGJrQnRZ
      VzUxWm1GamRIVnlaWEl0Ym1WME1Ga3dFd1lIS29aSXpqMENBUVlJS29aSQp6ajBEQVFjRFFnQUUx
      ZWxib01nRis5U3ppVjZLTWZTWHptc1N2SWRjZWFsMDVBSEt3dUgzOXlzQTkzY1BYOXMyCkU0WVVm
      RzBBVElQUmYrbHZubWhoOXo4ZXptNEU3SHUzaHFPQ0FTRXdnZ0VkTUE0R0ExVWREd0VCL3dRRUF3
      SUgKZ0RBTUJnTlZIUk1CQWY4RUFqQUFNQjBHQTFVZERnUVdCQlNQcXBMajd4WGJGVktUc1hLeERH
      UzI4cmE3M3pBZgpCZ05WSFNNRUdEQVdnQlNwL1VRU2F3TVNYNWhNNzBsQjRKakZOWDFDK2pBakJn
      TlZIUkVFSERBYWdoaGpZUzEwCmIyOXNjeTAxT1Raa09EWTVaR1F0Y1hSNE5uZ3dnWmNHQ0NvREJB
      VUdCd2dCQklHS2V5SmhkSFJ5Y3lJNmV5SmgKWW1GakxtbHVhWFFpT2lKMGNuVmxJaXdpWVdSdGFX
      NGlPaUowY25WbElpd2lhR1l1UVdabWFXeHBZWFJwYjI0aQpPaUp0WVc1MVptRmpkSFZ5WlhJaUxD
      Sm9aaTVGYm5KdmJHeHRaVzUwU1VRaU9pSkJaRzFwYmtCdFlXNTFabUZqCmRIVnlaWEl0Ym1WMElp
      d2lhR1l1Vkhsd1pTSTZJbUZrYldsdUluMTlNQW9HQ0NxR1NNNDlCQU1DQTBjQU1FUUMKSUJlSndj
      QlRWSlFNc1JYYS9FYUNlUEJBdVUwc1laRnZrd2xubHU2d1RlcGVBaUJ1VWJmTy9HRVVaZzdwUE1j
      TgpKQ0huNG9pWUhkQzNraDI0dzFGemtydnJ4UT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      Qg4KBFNIQTISBlNIQTI1NkqBBi0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlDQ3pDQ0Fi
      S2dBd0lCQWdJVVQ4UmJnbHRRUjJsQXE4SGQ4U0JMZkE2QUQ1OHdDZ1lJS29aSXpqMEVBd0l3ClpE
      RUxNQWtHQTFVRUJoTUNRMGd4RHpBTkJnTlZCQWdNQmxwMWNtbGphREVQTUEwR0ExVUVCd3dHV25W
      eWFXTm8KTVJVd0V3WURWUVFLREF4TllXNTFabUZqZEhWeVpYSXhIREFhQmdOVkJBTU1FMk5oTG0x
      aGJuVm1ZV04wZFhKbApjaTF1WlhRd0hoY05Nakl3TmpJeE1UQXdOakUyV2hjTk1qVXdOREV3TVRB
      d05qRTJXakJrTVFzd0NRWURWUVFHCkV3SkRTREVQTUEwR0ExVUVDQXdHV25WeWFXTm9NUTh3RFFZ
      RFZRUUhEQVphZFhKcFkyZ3hGVEFUQmdOVkJBb00KREUxaGJuVm1ZV04wZFhKbGNqRWNNQm9HQTFV
      RUF3d1RZMkV1YldGdWRXWmhZM1IxY21WeUxXNWxkREJaTUJNRwpCeXFHU000OUFnRUdDQ3FHU000
      OUF3RUhBMElBQkhueDZDek0xNVRXdHMweUJwWmQ5RGdnM1JwUERpQytidFl0Cm5wV0s0NW5Ma2tM
      cXh5Q1hhMWJNcUplbEVuYWFLQ3VVT2dTNDZqckpmZG1pamluN3hGZWpRakJBTUE4R0ExVWQKRXdF
      Qi93UUZNQU1CQWY4d0RnWURWUjBQQVFIL0JBUURBZ0dtTUIwR0ExVWREZ1FXQkJTcC9VUVNhd01T
      WDVoTQo3MGxCNEpqRk5YMUMrakFLQmdncWhrak9QUVFEQWdOSEFEQkVBaUFWWk9yamVSRWdvV1NR
      bTFLTDBQVGs0MDF1CjdqNWpWcTdZWkoxcjE4NVNHd0lnS0R2T2VJYjBkWkVvREhsSS9PMk01QXh1
      enE5bHUwSXdaUkpIMzYvTDlvWT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoaBkFkbWlucyI4
      CgdXcml0ZXJzEi0SIwgBEh8SCBIGCAESAggAGhMSEQoPbWFudWZhY3R1cmVyTVNQGgZBZG1pbnMi
      OQoGQWRtaW5zEi8SJQgBEiESCBIGCAESAggAGhUSEwoPbWFudWZhY3R1cmVyTVNQEAEaBkFkbWlu
      cyI8CgtFbmRvcnNlbWVudBItEiMIARIfEggSBggBEgIIABoTEhEKD21hbnVmYWN0dXJlck1TUBoG
      QWRtaW5zIjgKB1JlYWRlcnMSLRIjCAESHxIIEgYIARICCAAaExIRCg9tYW51ZmFjdHVyZXJNU1Aa
      BkFkbWlucyoGQWRtaW5zEq4WCgpjYXJyaWVyTVNQEp8WGrsUCgNNU1ASsxQSqBQSpRQKCmNhcnJp
      ZXJNU1AS5QUtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQjl6Q0NBWjZnQXdJQkFnSVVO
      OWJBOUh1VU9ETUxMU0NjajBNNEtlNENabmd3Q2dZSUtvWkl6ajBFQXdJdwpXakVMTUFrR0ExVUVC
      aE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdE
      Z1lEVlFRS0RBZERZWEp5YVdWeU1SY3dGUVlEVlFRRERBNWpZUzVqWVhKeWFXVnlMVzVsZERBZUZ3
      MHkKTWpBMk1qRXhNREE0TVRaYUZ3MHlOVEEwTVRBeE1EQTRNVFphTUZveEN6QUpCZ05WQkFZVEFr
      ZENNUTh3RFFZRApWUVFJREFaTWIyNWtiMjR4RHpBTkJnTlZCQWNNQmt4dmJtUnZiakVRTUE0R0Ex
      VUVDZ3dIUTJGeWNtbGxjakVYCk1CVUdBMVVFQXd3T1kyRXVZMkZ5Y21sbGNpMXVaWFF3V1RBVEJn
      Y3Foa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3TkMKQUFROXoxcDM1ZVNPQ1lkbEJPbDYxTDh5RHlHeG5k
      azBRTXhTektKYkFRZGF4cDdlK3NFMmF6VnZYMnJUUDlqTQpiM0lvNEUzRWlFQTI4blIyNllPNnFz
      QjVvMEl3UURBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUE0R0ExVWREd0VCCi93UUVBd0lCcGpBZEJn
      TlZIUTRFRmdRVXV0bkM1c3lBUm1FcVdoNmFFSGpkNHVMVUw5WXdDZ1lJS29aSXpqMEUKQXdJRFJ3
      QXdSQUlnQjFDMmtzMkx4RUI0VUxYWnRtdTBVdzNDZWRrUFJ0TnBLc2h1WndUdDdzTUNJQjVYYTRB
      bwo1bTQxZEkzb3RVQlNTejRHZ3lVODV6aE1BZE5WZEpzTnd2bW0KLS0tLS1FTkQgQ0VSVElGSUNB
      VEUtLS0tLQoitggtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQzdqQ0NBcFNnQXdJQkFn
      SVVYWEo4UmhkdEhHRFpoT0Z3SDk0N3NLTE1Cc3d3Q2dZSUtvWkl6ajBFQXdJdwpXakVMTUFrR0Ex
      VUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1S
      QXdEZ1lEVlFRS0RBZERZWEp5YVdWeU1SY3dGUVlEVlFRRERBNWpZUzVqWVhKeWFXVnlMVzVsZERB
      ZUZ3MHkKTWpBMk1qRXhNREUxTURCYUZ3MHlNekEyTWpFeE1ESXdNREJhTUhneEN6QUpCZ05WQkFZ
      VEFrZENNUnN3R1FZRApWUVFIRXhJMU1TNDFNQzh0TUM0eE15OU1iMjVrYjI0eEVEQU9CZ05WQkFv
      VEIwTmhjbkpwWlhJeEhqQU1CZ05WCkJBc1RCV0ZrYldsdU1BNEdBMVVFQ3hNSFkyRnljbWxsY2pF
      YU1CZ0dBMVVFQXd3UlFXUnRhVzVBWTJGeWNtbGwKY2kxdVpYUXdXVEFUQmdjcWhrak9QUUlCQmdn
      cWhrak9QUU1CQndOQ0FBVEI3NE1XdzNrU2tGcFJQR1RHYkFXNgptdTBUYU9vbUdiK0xIR0UvdVNu
      Zjhlc0Y1MG1JbW5zdGNQQnAyM3ZhcDNiZy9oS3puemxyRFlYRzh0R0VpT0RFCm80SUJHRENDQVJR
      d0RnWURWUjBQQVFIL0JBUURBZ2VBTUF3R0ExVWRFd0VCL3dRQ01BQXdIUVlEVlIwT0JCWUUKRkFP
      djcreGhNTWtSNE4xRHVBd1dwLy82MFBtNE1COEdBMVVkSXdRWU1CYUFGTHJad3ViTWdFWmhLbG9l
      bWhCNAozZUxpMUMvV01DUUdBMVVkRVFRZE1CdUNHV05oTFhSdmIyeHpMVFk1TkdaaU5XUTJZbVl0
      T0haelptNHdnWTBHCkNDb0RCQVVHQndnQkJJR0FleUpoZEhSeWN5STZleUpoWW1GakxtbHVhWFFp
      T2lKMGNuVmxJaXdpWVdSdGFXNGkKT2lKMGNuVmxJaXdpYUdZdVFXWm1hV3hwWVhScGIyNGlPaUpq
      WVhKeWFXVnlJaXdpYUdZdVJXNXliMnhzYldWdQpkRWxFSWpvaVFXUnRhVzVBWTJGeWNtbGxjaTF1
      WlhRaUxDSm9aaTVVZVhCbElqb2lZV1J0YVc0aWZYMHdDZ1lJCktvWkl6ajBFQXdJRFNBQXdSUUlo
      QU1keEIyNTU1SHM3QUpqeWVnbFpnazN0cXNoY0JjRVQ3ajIvdlpKU2VDa2EKQWlCY2RlZmRldEp4
      ZnFFQ2RuTVpsZllwMzlVMVBjUS9uTC9ZRnJtMlBnUENEZz09Ci0tLS0tRU5EIENFUlRJRklDQVRF
      LS0tLS0KQg4KBFNIQTISBlNIQTI1NkrlBS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlC
      OXpDQ0FaNmdBd0lCQWdJVU45YkE5SHVVT0RNTExTQ2NqME00S2U0Q1puZ3dDZ1lJS29aSXpqMEVB
      d0l3CldqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVC
      d3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkRFlYSnlhV1Z5TVJjd0ZRWURWUVFEREE1allTNWpZ
      WEp5YVdWeUxXNWxkREFlRncweQpNakEyTWpFeE1EQTRNVFphRncweU5UQTBNVEF4TURBNE1UWmFN
      Rm94Q3pBSkJnTlZCQVlUQWtkQ01ROHdEUVlEClZRUUlEQVpNYjI1a2IyNHhEekFOQmdOVkJBY01C
      a3h2Ym1SdmJqRVFNQTRHQTFVRUNnd0hRMkZ5Y21sbGNqRVgKTUJVR0ExVUVBd3dPWTJFdVkyRnlj
      bWxsY2kxdVpYUXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQwpBQVE5ejFwMzVlU09D
      WWRsQk9sNjFMOHlEeUd4bmRrMFFNeFN6S0piQVFkYXhwN2Urc0UyYXpWdlgyclRQOWpNCmIzSW80
      RTNFaUVBMjhuUjI2WU82cXNCNW8wSXdRREFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQTRHQTFVZER3
      RUIKL3dRRUF3SUJwakFkQmdOVkhRNEVGZ1FVdXRuQzVzeUFSbUVxV2g2YUVIamQ0dUxVTDlZd0Nn
      WUlLb1pJemowRQpBd0lEUndBd1JBSWdCMUMya3MyTHhFQjRVTFhadG11MFV3M0NlZGtQUnROcEtz
      aHVad1R0N3NNQ0lCNVhhNEFvCjVtNDFkSTNvdFVCU1N6NEdneVU4NXpoTUFkTlZkSnNOd3ZtbQot
      LS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tChoGQWRtaW5zIjQKBkFkbWlucxIqEiAIARIcEggSBggB
      EgIIABoQEg4KCmNhcnJpZXJNU1AQARoGQWRtaW5zIjcKC0VuZG9yc2VtZW50EigSHggBEhoSCBIG
      CAESAggAGg4SDAoKY2Fycmllck1TUBoGQWRtaW5zIjMKB1JlYWRlcnMSKBIeCAESGhIIEgYIARIC
      CAAaDhIMCgpjYXJyaWVyTVNQGgZBZG1pbnMiMwoHV3JpdGVycxIoEh4IARIaEggSBggBEgIIABoO
      EgwKCmNhcnJpZXJNU1AaBkFkbWlucyoGQWRtaW5zGkAKFUNoYW5uZWxDcmVhdGlvblBvbGljeRIn
      EgwIAxIICgZBZG1pbnMaFy9DaGFubmVsL09yZGVyZXIvQWRtaW5zKhcvQ2hhbm5lbC9PcmRlcmVy
      L0FkbWlucyItCgZBZG1pbnMSIxIICAESBBICEgAaFy9DaGFubmVsL09yZGVyZXIvQWRtaW5zKhcv
      Q2hhbm5lbC9PcmRlcmVyL0FkbWlucxomChBIYXNoaW5nQWxnb3JpdGhtEhISCAoGU0hBMjU2GgZB
      ZG1pbnMaLQoZQmxvY2tEYXRhSGFzaGluZ1N0cnVjdHVyZRIQEgYI/////w8aBkFkbWlucxpOChBP
      cmRlcmVyQWRkcmVzc2VzEjoSHwodb3JkZXJlcjEuc3VwcGx5Y2hhaW4tbmV0OjcwNTAaFy9DaGFu
      bmVsL09yZGVyZXIvQWRtaW5zGiQKDENhcGFiaWxpdGllcxIUEgoKCAoEVjJfMBIAGgZBZG1pbnMi
      IgoHUmVhZGVycxIXEg0IAxIJCgdSZWFkZXJzGgZBZG1pbnMiIgoHV3JpdGVycxIXEg0IAxIJCgdX
      cml0ZXJzGgZBZG1pbnMiIgoGQWRtaW5zEhgSDggDEgoKBkFkbWlucxACGgZBZG1pbnMqBkFkbWlu
      cxoOCgQKAgoACgAKAAoACgA=

    config:
      pod:
        resources:
          limits:
            memory: 512M
            cpu: 1
          requests:
            memory: 512M
            cpu: 0.5
