apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: manufacturer-ambassador-job
  namespace: manufacturer-bes
  annotations:
    flux.weave.works/automated: "false"      
spec:
  releaseName: manufacturer-ambassador-job
  chart:
    path: platforms/hyperledger-besu/charts/generate_ambassador_certs
    git: https://github.com/jagpreetsinghsasan/bevel.git
    ref: localtest
  values:
    metadata:
      name: manufacturer-ambassador-job
      namespace: manufacturer-bes      
    image:      
      alpineutils: hyperledgerlabs/alpine-utils:1.0
      pullSecret: regcred
    network:
      tmtls: True
    node:
      name: manufacturer
      clientport: 8888 
    vault:
      address: http://192.168.1.10:8200
      secretengine: secretsv2
      authpath: besumanufacturer
      rootcasecret: secretsv2/data/manufacturer-bes/crypto/ambassadorcerts/rootca
      ambassadortlssecret: secretsv2/data/manufacturer-bes/crypto/manufacturer/tls
      role: vault-role
      serviceaccountname: vault-auth
    subject:
      ambassadortls: CN=DLT Root CA/OU=DLT/O=DLT/L=London/C=GB
    opensslVars:
      domain_name_pub: manufacturer.manufacturer-bes.svc.cluster.local
      domain_name_priv: manufacturer.manufacturer-bes
      domain_name_tessera: manufacturer-tessera.manufacturer-bes
    healthcheck: 
      retries: 10
      sleepTimeAfterError: 2
