apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: warehouse-ambassador-job
  namespace: warehouse-bes
  annotations:
    flux.weave.works/automated: "false"      
spec:
  releaseName: warehouse-ambassador-job
  chart:
    path: platforms/hyperledger-besu/charts/generate_ambassador_certs
    git: https://github.com/jagpreetsinghsasan/bevel.git
    ref: localtest
  values:
    metadata:
      name: warehouse-ambassador-job
      namespace: warehouse-bes      
    image:      
      alpineutils: hyperledgerlabs/alpine-utils:1.0
      pullSecret: regcred
    network:
      tmtls: True
    node:
      name: warehouse
      clientport: 8888 
    vault:
      address: http://192.168.1.10:8200
      secretengine: secretsv2
      authpath: besuwarehouse
      rootcasecret: secretsv2/data/warehouse-bes/crypto/ambassadorcerts/rootca
      ambassadortlssecret: secretsv2/data/warehouse-bes/crypto/warehouse/tls
      role: vault-role
      serviceaccountname: vault-auth
    subject:
      ambassadortls: CN=DLT Root CA/OU=DLT/O=DLT/L=London/C=GB
    opensslVars:
      domain_name_pub: warehouse.warehouse-bes.svc.cluster.local
      domain_name_priv: warehouse.warehouse-bes
      domain_name_tessera: warehouse-tessera.warehouse-bes
    healthcheck: 
      retries: 10
      sleepTimeAfterError: 2
