apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: carrier-ambassador-job
  namespace: carrier-bes
  annotations:
    flux.weave.works/automated: "false"      
spec:
  releaseName: carrier-ambassador-job
  chart:
    path: platforms/hyperledger-besu/charts/generate_ambassador_certs
    git: https://github.com/jagpreetsinghsasan/bevel.git
    ref: localtest
  values:
    metadata:
      name: carrier-ambassador-job
      namespace: carrier-bes      
    image:      
      alpineutils: hyperledgerlabs/alpine-utils:1.0
      pullSecret: regcred
    network:
      tmtls: True
    node:
      name: carrier
      clientport: 8888 
    vault:
      address: http://192.168.1.10:8200
      secretengine: secretsv2
      authpath: besucarrier
      rootcasecret: secretsv2/data/carrier-bes/crypto/ambassadorcerts/rootca
      ambassadortlssecret: secretsv2/data/carrier-bes/crypto/carrier/tls
      role: vault-role
      serviceaccountname: vault-auth
    subject:
      ambassadortls: CN=DLT Root CA/OU=DLT/O=DLT/L=London/C=GB
    opensslVars:
      domain_name_pub: carrier.carrier-bes.svc.cluster.local
      domain_name_priv: carrier.carrier-bes
      domain_name_tessera: carrier-tessera.carrier-bes
    healthcheck: 
      retries: 10
      sleepTimeAfterError: 2
